version: "3"

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - ./.env
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    driver_opts:
      type: none
      o: bind
      device: /home/aachhoub/data/mariadb_data
  wordpress_data:
    driver_opts:
      type: none
      o: bind
      device: /home/aachhoub/data/wordpress_data

networks:
  inception:
    driver: bridge